#!/bin/bash

error()
{
if [ "$?" != "0" ]; then
kill $(ps aux | grep -m 1 'Select Services' | awk 'BEGIN { FS = " " } ; { print $2 }') &>2
kill $(ps aux | grep -m 1 'daemondialog' | grep bash | awk 'BEGIN { FS = " " } ; { print $2 }') &>2
exit 1
fi
}

# get status of services
if [ -z $( /etc/rc.d/nfs-common status | grep -o STARTED) ]; then
	nfscstat=False
else
	nfscstat=True
fi

if [ -z $( /etc/rc.d/nfs-server status | grep -o STARTED) ]; then
	nfsvstat=False
else
	nfsvstat=True
fi
	
if [ -z "$(ps -e | grep smbd)" ]; then
	smbstat="False"
else
	smbstat="True"
fi

if [ -z "$(ps -e | grep sshd)" ]; then
	sshstat="False"
else
	sshstat="True"
fi

if [ -z "$(ps -e | grep cupsd)" ]; then
	cupsstat="False"
else
	cupsstat="True"
fi

if [ -z "$(ps -e | grep avahi-daemon)" ]; then
	avahistat="False"
else
	avahistat="True"
fi

if [ -z "$(ps -e | grep bluetoothd)" ]; then
	bluestat="False"
else
	bluestat="True"
fi

# create window
input=$(yad --width=500 --height=300 --list \
	  --separator=" " \
          --title="Select Services" \
          --column="Status" --column="Service" --column="Description" \
	  --print-column=2 \
	  --hide-column=2 \
	  --center \
	  --checklist \
	    $nfscstat "nfs-common" "Network File Sharing Client Service" \
            $nfsvstat "nfs-server" "Network File Sharing Server" \
            $smbstat "samba" "Windows File Server" \
	    $sshstat "ssh" "Secure Shell Server" \
	    $cupsstat "cups" "Printing Services" \
	    $avahistat "avahi" "AVAHI DNS Daemon" \
	    $bluestat "bluetoothd" "Bluetooth Daemon")
error
nc=0
ns=0
smb=0
sshs=0
cups=0
avahi=0
blue=0

for i in $input ; do
	case $i in
	nfs-common	)	nc=1; [ $nfscstat == True ] || gksudo /etc/rc.d/nfs-common start; error ;;
	nfs-server	)	ns=1; [ $nfsvstat == True ] || gksudo /etc/rc.d/nfs-server start; error ;;
	samba		)	smb=1; [ $smbstat == True ] || gksudo /etc/rc.d/samba start; error ;;
	ssh		)	sshs=1; [ $sshstat == True ] || gksudo /etc/rc.d/sshd start; error ;;
	cups		)	cups=1; [ $cupsstat == True ] || gksudo /etc/rc.d/cupsd start; error ;;
	avahi		)	avahi=1; [ $avahistat == True ] || gksudo /etc/rc.d/avahi-daemon start; error ;;
	bluetoothd	)	blue=1; [ $bluestat == True ] || gksudo /etc/rc.d/bluetooth start; error; blueman-applet;;
	esac
done

[ $nc == 1 ] || [ $nfscstat == False ] || gksudo /etc/rc.d/nfs-common stop
error
[ $ns == 1 ] || [ $nfsvstat == False ] || gksudo /etc/rc.d/nfs-server stop
error
[ $smb == 1 ] || [ $smbstat == False ] || gksudo /etc/rc.d/samba stop
error
[ $sshs == 1 ] || [ $sshstat == False ] || gksudo /etc/rc.d/sshd stop
error
[ $cups == 1 ] || [ $cupsstat == False ] || gksudo /etc/rc.d/cupsd stop
error
[ $avahi == 1 ] || [ $avahistat == False ] || gksudo /etc/rc.d/avahi-daemon stop
error
[ $blue == 1 ] || [ $bluestat == False ] || gksudo /etc/rc.d/bluetooth stop
